apiVersion: v1
kind: Pod
metadata:
  name: declarative-pod-nginx
  labels:
    env: demo
    type: frontend
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    ports:
    - containerPort: 80
