apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-nginx
  labels:
    env: demo
spec:
  replicas: 3
  template:
    metadata:
      labels:
        env: demo
      name : nginx
    spec:
      containers: 
      - name: nginx-container
        image: nginx:latest
        ports:
        - containerPort: 80
